### ISSUE TITLE
program error "AttributeError: 'ImageFolder' object has no attribute 'keys'"

### ISSUE THREAD

**Issue by Lululu100** [raphaelmemmesheimer/skeleton-dml#9]
Hi, your work is excellent. I conducted the experiment according to your Settings and encountered the following problems. If you know what caused this, please reply. Looking forward to your reply very much.

Traceback (most recent call last):
  File "E:\Study\Code\skeleton-dml-main\train.py", line 353, in <module>
    train_app()
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\hydra\main.py", line 20, in decorated_main
    run_hydra(
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 171, in run_hydra
    hydra.run(
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\hydra.py", line 82, in run
    return run_job(
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "E:\Study\Code\skeleton-dml-main\train.py", line 333, in train_app
    trainer = trainers.TrainWithClassifier(models,
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\pytorch_metric_learning\trainers\base_trainer.py", line 61, in __init__
    self.verify_dict_keys()
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\pytorch_metric_learning\trainers\base_trainer.py", line 266, in verify_dict_keys
    self.schema.verify(self)
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\pytorch_metric_learning\utils\key_checker.py", line 16, in verify
    self._verify_prop(getattr(obj, k, None), k, v)
  File "D:\software\Anaconda3\envs\pytorch\lib\site-packages\pytorch_metric_learning\utils\key_checker.py", line 25, in _verify_prop
    for k in obj.keys():
AttributeError: 'ImageFolder' object has no attribute 'keys'

**Comment by Lululu100** [comment]
I solved this problem by matching the versions of different packages.
